import { createTheme, Theme } from "@mui/material";

// This must be imported here to provide default styling for date pickers and components in mui lab. 
// See documentation: 
//  - https://mui.com/x/react-date-pickers/getting-started/
//  - https://mui.com/material-ui/about-the-lab/
import type { } from '@mui/lab/themeAugmentation';
import type { } from '@mui/x-date-pickers/themeAugmentation';

export enum AppThemeName {
    Dark = "dark",
    Light = "light"
}

export type AppThemeProps = {
    theme: Theme;
    name: AppThemeName;
}

export const DarkAppTheme: AppThemeProps = {
    name: AppThemeName.Dark,
    theme: createTheme({
        palette: {
            mode: 'dark',
            primary: {
                main: "#196E45"
                // light: ""       // Autogenerated from main value   
                // dark: ""
                // contrastText: ""
            },
            secondary: {
                main: "#90CAF9"
                // main: "#90CAF9"
                // light: ""       // Autogenerated from main value   
                // dark: ""
                // contrastText: "
            },
            background: {
                default: "#1A1A1A",
                paper: "#212121"
            },
            text: {
                primary: "#F0F0F0",
                secondary: "#E0E0E0"
            },
            // ---------------------------------
            // Autogenerated colors:
            //      * Uncomment to override    
            //      * Default colors can be found here: https://mui.com/material-ui/customization/palette/   
            // ---------------------------------
            // primary: {          
            //     main: "",        
            //     light: "",            
            //     dark: "",
            //     contrastText: "",
            // },
            // error: {
            //     main: "",
            //     light: "",
            //     dark: "",
            //     contrastText: "",
            // },
            // warning: {
            //     main: "",
            //     light: "",
            //     dark: "",
            //     contrastText: "",
            // },
            // info: {
            //     main: "",
            //     light: "",
            //     dark: "",
            //     contrastText: "",
            // },
            // success: {
            //     main: "",
            //     light: "",
            //     dark: "",
            //     contrastText: "",
            // }
        }
    })
};
export const LightAppTheme: AppThemeProps = {
    name: AppThemeName.Light,
    theme: createTheme({
        palette: {
            mode: 'light',
            primary: {
                main: "#196E45",
                //light: "",        // Autogenerated from main value   
                //dark: "",
                //contrastText: "",
            },
            secondary: {
                main: "#1976D2"
                //light: "",        // Autogenerated from main value   
                //dark: "",
                //contrastText: "",
            },
            background: {
                default: "#F5F6F5",
                paper: "#F9F9F9"
            },
            text: {
                primary: "#202020",
                secondary: "#303030"
            },
            action: {
                hover: "#C3C3C377"
            }
            // ---------------------------------
            // Autogenerated colors:
            //      * Uncomment to override 
            //      * Default colors can be found here: https://mui.com/material-ui/customization/palette/   
            // ---------------------------------
            // primary: {           
            //     main: "",        
            //     light: "",            
            //     dark: "",
            //     contrastText: "",
            // },
            // error: {
            //     main: "",
            //     light: "",
            //     dark: "",
            //     contrastText: "",
            // },
            // warning: {
            //     main: "",
            //     light: "",
            //     dark: "",
            //     contrastText: "",
            // },
            // info: {
            //     main: "",
            //     light: "",
            //     dark: "",
            //     contrastText: "",
            // },
            // success: {
            //     main: "",
            //     light: "",
            //     dark: "",
            //     contrastText: "",
            // }
        },
    })
};
