export enum Tone {
    Gb = "Gb",
    Db = "Db",
    Ab = "Ab",
    Eb = "Eb",
    Bb = "Bb",
    F  = "F",
    C  = "C",
    G  = "G",
    D  = "D",
    A  = "A",
    E  = "E",
    H  = "H",
    Fs = "F#",
    Cs = "C#",
    Gs = "G#",
    Ds = "D#",
    As = "A#",
}