INSERT INTO sheet_archive(title, is_public, root_path, filename) VALUES
('A Swinging Safari',               false,  'files/private/', 'notearkiv/A Swinging Safari.pdf'),
('Another Brick in the Wall',       false,  'files/private/', 'notearkiv/Another Brick in the Wall.pdf'),
('Bruremarsj',                      false,  'files/private/', 'notearkiv/Bruremarsj.pdf'),
('Can-Can',                         false,  'files/private/', 'notearkiv/Can-Can.pdf'),          
('Dixieland Strut',                 false,  'files/private/', 'notearkiv/Dixieland Strut.pdf'),
('Dyreparkens Røvermarsj',          false,  'files/private/', 'notearkiv/Dyreparkens Røvermarsj.pdf'),
('Funkytown',                       false,  'files/private/', 'notearkiv/Funkytown.pdf'),
('Gonna Fly Now',                   false,  'files/private/', 'notearkiv/Gonna Fly Now.pdf'),
('Happy',                           false,  'files/private/', 'notearkiv/Happy.pdf'),
('Holmenkollmarsjen',               false,  'files/private/', 'notearkiv/Holmenkollmarsjen.pdf'),
('Ice Cream',                       false,  'files/private/', 'notearkiv/Ice Cream.pdf'),
('Killing in the Name',             false,  'files/private/', 'notearkiv/Killing in the Name.pdf'),
('Norge i Rødt, Hvitt og Blått',    false,  'files/private/', 'notearkiv/Norge i Rødt, Hvitt og Blått.pdf'),
('Olsenbanden',                     false,  'files/private/', 'notearkiv/Olsenbanden.pdf'),
('The Bare Necessities',            false,  'files/private/', 'notearkiv/The Bare Necessities.pdf');