INSERT INTO quote(quote_id, utterer, quote) VALUES
(1,	    'Simen s. til Simen h. (aka pompel til pilt)	Simen s',  '"Se på det monsteret der da!"\n\t \n\t * Simen s. viser telefonen til Simen h. *\n\t \n\t Simen h: "...ehmm... men det er jo..."\n\t Simen s: "Nei, ignorer fargen da!"'),
(2,	    'Jørgen og Eirik h. den 29 januar',	                        'Eirik h.: I dag er den offisielle nynorsk dagen. De har vært smarte ved å velge en dag som...\n*Jørgen avbryter*: ...bare kommer 4 ganger i året.'),
(3,	    'Magnhild om Trondheims Studentersangforening',	            'De var flinke! Jeg ble skikkelig kåt ... of guard!'),
(4,	    'Jørgen på arr. og pils',	                                'D einaste en kan stole på, e stål!'),
(5,	    'Sjur',	                                                    'Noen i Motstanden: Hva er SMASH?\nSjur: Jeg føler det er litt som orgie!'),
(6,	    'Eirik f. om Simen h.',	                                    'Mora di er deilig, no offense.\nAt det har kommet ut fra slufsa hennes, det er utrolig!'),
(7,	    'Sjur til Torstein',	                                    'Hvis jeg kan få ta deg i ræven, så kan du få ta meg i ræven.'),
(8,	    'Sjur',	                                                    'Kan man pule en boks tomater? Jeg tror det må være sånn helt ... decent.'),
(9,	    'Simen h.',	                                                'Slikk det opp, det går fint!'),
(10,    'Eirik f. til Torstein',	                                'Ikke ta på meg!'),
(11,    'Magnhild',	                                                'Jeg vet ikke hva dette har med bæsj å gjøre.'),
(12,    'Sjur',	                                                    'Nå skal du ta deg et glass rødvin og roe ned den mensinga!'),
(13,    'Eirik f. og Magnhild',    	                                'Eirik f: Er hun pen eller ikke?\nMagnhild svarer: Er det en mann?!'),
(14,    'Torstein',	                                                'Fløte er gøy!'),
(15,    'Sjur',	                                                    'Å nei, har jeg sovnet i stampen?!'),
(16,    'Torstein til Simen h.',	                                'Du har skikkelig Big Dick-energy!'),
(17,    'Nina',	                                                    'Hans Olav: Du har ikke behandlet kroppen din sunt; du har dukket masse alkohol.\n\nNina: Ja, MEN jeg har spist HVER dag kl 1700!'),
(18,    'Nina til Gunnar',	                                        'Gunnar: jeg må på do.\nNina: HAR DU HØRT OM BUSKEN?'),
(19,    'Eirik Furuholt	Eirik kl 21:35',                            'Jeg skal inn på samfundet SEINEST kl 2100!'),
(20,    'Eirik Furuholt og Ole Tobias',	                            'Eirik: Hva syns du om staven min?\nOle Tobias: Den er imponerende lang!'),
(21,    'Torstein til Gunnar Sæther',	                            'Så du sier man må være muskuløs for å være prest?!'),
(22,    'Vekter fra Sykkylven',	                                    'Lat att grinda, kyra frys!'),
(23,    'Sverre',	                                                'Gunnar tykkjer forteljinga skal slutte med "snipp snapp snute, no er eventyret ute". Sverre seier "Nei, det kan ein aldri seie, for eventyr er alltid in!"'),
(24,    'Christian (til sin kone på første øvelse)', 	            'Jeg tror jeg har blitt med i et korps'),
(25,    'Eirik til Sjur',	                                        'Du er trommis og du kan ikke slå rytmen til jenter en gang??!'),
(26,    'Hans Olav',	                                            'Den konfirmasjonen er det værste SMASH-et jeg har vært på!'),
(27,    'Torstein',	                                                'Det blir spurt om hvem noen har tilgang til P15.\nTorstein: jeg har tilgang, men jeg har mistet studentkortet mitt.\nNina: Hvorfor kjøper du ikke nytt?\nTorstein: Fordi jeg har mistet bankkortet mitt. Men det er ikke alt jeg har mistet, jeg har også mistet lommeboka mi. Men ikke bare har jeg mistet lommeboka mi, jeg har også mistet Jobbkortet mitt. Og ikke bare har jeg mistet Jobbkortet, jeg har også mistet passet mitt.  ...men jeg har tilgang.'),
(28,    'Nina',	                                                    'Hans Olav: Blæsen er det sangkor, er det ikke?\nNina til Gunnar M.: Vi dreper''n!'),
(29,    'Eirik F',	                                                'Jeg får litt lyst til å ligge med søsteren min'),
(30,    'Eirik Husebø og Gunnar Myhre på lyche',	                '*Det snakkes om hakkebakkeskogen*\n\nEirik h: Det er turboneger, sant?\nGunnnar M: HÆÆÆ, DETTE HAR INGENTING MED TURBONEGER Å GJØRE!\nEirik H: Jeg sa Thorbjørn Egner...'),
(31,    'Sindre',	                                                'Du skjønner ikke, jeg er heavy metal!'),
(32,    'Magnhild',	                                                'De vil bli knulla av dyr!'),
(33,    'Torstein (om Bergstua)',	                                'Det huset her er cursed, jeg får hele tida lyst på øl!'),
(34,    'Nina (om pent.no)',	                                    'Hvis du er midt mellom begge to så er du circa ish på kanskje!'),
(35,    'Eirik til Eirik',	                                        'Eirik, er du singel?');

INSERT INTO ping VALUES ('Pong from the database');