INSERT INTO sheet_archive(title, root_path, filename) VALUES
('A Swinging Safari',               'files/', 'notearkiv/A Swinging Safari.pdf'),
('Another Brick in the Wall',       'files/', 'notearkiv/Another Brick in the Wall.pdf'),
('Bruremarsj',                      'files/', 'notearkiv/Bruremarsj.pdf'),
('Can-Can',                         'files/', 'notearkiv/Can-Can.pdf'),          
('Dixieland Strut',                 'files/', 'notearkiv/Dixieland Strut.pdf'),
('Dyreparkens Røvermarsj',          'files/', 'notearkiv/Dyreparkens Røvermarsj.pdf'),
('Funkytown',                       'files/', 'notearkiv/Funkytown.pdf'),
('Gonna Fly Now',                   'files/', 'notearkiv/Gonna Fly Now.pdf'),
('Happy',                           'files/', 'notearkiv/Happy.pdf'),
('Holmenkollmarsjen',               'files/', 'notearkiv/Holmenkollmarsjen.pdf'),
('Ice Cream',                       'files/', 'notearkiv/Ice Cream.pdf'),
('Killing in the Name',             'files/', 'notearkiv/Killing in the Name.pdf'),
('Norge i Rødt, Hvitt og Blått',    'files/', 'notearkiv/Norge i Rødt, Hvitt og Blått.pdf'),
('Olsenbanden',                     'files/', 'notearkiv/Olsenbanden.pdf'),
('The Bare Necessities',            'files/', 'notearkiv/The Bare Necessities.pdf');