INSERT INTO quote(utterer, quote) VALUES
('Gustav K. til Albert E.',                             '"Se på det monsteret der da!"\n\n* Kirchhoff. viser telefonen til Einstein. *\n\nEinstein: "...ehmm... men det er jo..."\nKirchhoff: "Nei, ignorer fargen da!"'),
('Gustav Kirchhoff',                                    'Gustav K.: I dag er den offisielle nynorsk dagen. De har vært smarte ved å velge en dag som...\n*Faraday avbryter*: ...bare kommer 4 ganger i året.'),
('Georg Ohm',                                           'De var flinke! Jeg ble skikkelig kåt ... of guard!'),
('Nikola Tesla',                                        'D einaste en kan stole på, e stål!'),
('Charles Coulomb',                                     'Noen i Motstanden: Hva er SMASH? Kirchhoff: Jeg føler det er litt som en orgie!'),
('Alessandro Volta om Niels Bohr',                      'Mora di er deilig, no offense. At det har kommet ut fra slufsa hennes, det er utrolig!'),
('Niels Bohr om Alfred Nobel',                          'Hvis jeg kan få ta deg i ræven, så kan du få ta meg i ræven.'),
('Alfred Nobel',                                        'Kan man pule en boks tomater? Jeg tror det må være sånn helt ... decent.'),
('Michael Faraday',                                     'Slikk det opp, det går fint!'),
('James Maxwell',                                       'Ikke ta på meg!'),
('Charles Darwin',                                      'Jeg vet ikke hva dette har med bæsj å gjøre.'),
('Thomas Edison',                                       'Nå skal du ta deg et glass rødvin og roe ned den mensinga!'),
('Isaac Newton og Charles Darwin',                      'Newton: Er hun pen eller ikke?\nDarwin svarer: Er det en mann?!'),
('Alan Turing',                                         'Fløte er gøy!'),
('Albert Einstein',                                     'Å nei, har jeg sovnet i stampen?!'), 
('Isaac Newton til Albert Einstein',                    'Du har skikkelig Big Dick-energy!'), 
('Pytagoras',                                           'Arkimedes: Du har ikke behandlet kroppen din sunt; du har dukket masse alkohol.\nPytagoras: Ja, MEN jeg har spist HVER dag kl 1700!'),
('Marie Curie',                                         'Maxwell: jeg må på do.\nCurie: HAR DU HØRT OM BUSKEN?'),
('Heinrich Hertz kl 21:35',                             'Jeg skal inn på samfundet SEINEST kl 2100!'),
('Michael Faraday og Nikola Tesla',                     'Faraday: Hva syns du om staven min?\nTesla: Den er imponerende lang!'),
('Galileo Galilei til Leonardo da Vinci',               'Så du sier man må være muskuløs for å være prest?!'),
('Vekter fra Sykkylven',                                'Lat att grinda, kyra frys!'),
('Stephen Hawking (til sin kone på første øvelse)',     'Jeg tror jeg har blitt med i et korps'),
('Pytagoras til Arkimedes',                             'Du er trommis og du kan ikke slå rytmen til jenter en gang??!'),
('Georg Ohm',                                           'Den konfirmasjonen er det værste SMASH-et jeg har vært på!'),
('James Maxwell',                                       'Det blir spurt om hvem noen har tilgang til P15.\n\nMaxwell: jeg har tilgang, men jeg har mistet studentkortet mitt.\n\nOhm: Hvorfor kjøper du ikke nytt?\n\nMaxwell: Fordi jeg har mistet bankkortet mitt. Men det er ikke alt jeg har mistet, jeg har også mistet lommeboka mi. Men ikke bare har jeg mistet lommeboka mi, jeg har også mistet Jobbkortet mitt. Og ikke bare har jeg mistet Jobbkortet, jeg har også mistet passet mitt. ...men jeg har tilgang.'),
('Charles Coulomb',                                     'Blæsen er det sangkor, er det ikke? '),
('Thomas Edison',                                       'Jeg får litt lyst til å ligge med søsteren min'),
('Marie Curie og Alessandro Volta',                     '*Det snakkes om hakkebakkeskogen*\n\nCurie: Det er turboneger, sant?\n\nVolta: HÆÆÆ, DETTE HAR INGENTING MED TURBONEGER Å GJØRE!\n\nCurie: Jeg sa Thorbjørn Egner...'),
('Stephen Hawking',                                     'Du skjønner ikke, jeg er heavy metal!'),
('Heinrich Hertz',                                      'De vil bli knulla av dyr'),
('Leonhard Euler',                                      'Det huset her er cursed, jeg får hele tida lyst på øl!'),
('Gustav Kirchhoff',                                    'Homenkollmarsjen, det er den eneste sangen jeg trenger noter på.\n\n...Og jeg kan ikke lese noter. Så det er den sangen jeg ikke kan!'),
('Albert Einstein',                                     'I har kun ei skje - og den kjøpte i på Fretex.'),
('Linus Torvalds',                                      'Ikkje ta på elektronikken min!'),
('Linus Torvalds',                                      'Sent på 17. mai kvelden 2021\n\nLinus til Alfred Nobel: Må vi hjem nå? Kan vi ikke vær så snill bli litt lenger?\n\nNobel: Men Alan Turing har dratt hjem\n\nLinus: Vi må dra NÅ, med én gang!!'),
('Joseph Fourier',                                      'Livet er ett elende uten øl, jeg må bare google hva elende er.') , 
('Niels Bohr',                                          'Æ har så lyst tell å sprenge stortinget av å tell!'),
('Isaac Newton',                                        'Det er sykt hvor høy man kan bli på gud ass!'),
('Thomas Edison om han burde stille til leder',         'Møkk er bedre en vakuum.'),
('Linus Torvalds',                                      'Alle e litt Alan Turing når de e full'),
('Leonhard Euler',                                      'Ingen:\n\nIngen:\n\nIngen:\n\nEuler: I mø sø jææækla pisse!'),
('Charles Darwin til Leonardo da Vinci',                'Du har kortslutta naså di du'),
('Thomas Edison',                                       'En... To... Jeg synest det er vanskelig å telle jeg!'),
('Leonardo da Vinci',                                   'Ærlighet varer lenge, men motstanden varer lengest'),
('Overhørt på jubball',                                 'Hva er greia med det orchesteret egentlig'),
('Pytagoras',                                           'Jeg kommer på SMASH!'),
('Georg Ohm',                                           'Kirchhoff: Vi har gitt trelle-navn til lånekappene.\n\nOhm: Det er vanskelig navn, vi kommer aldri til å legge merke til om en av de forsvinner. Dere burde heller gitt de noe vi enkelt husker, slik som bæsj, tiss, promp.\n\nKirchhoff: Dere kan jo finne på et eget navn til den lånekappe dere lager nå.\n\nOhm: Da blir det Bæsj..'),
('Er dere rumpeldunklaget til Smygard??',               'Er dere rumpeldunklaget til Smygard??'),
('Joseph Fourier',                                      'Men.. du har jo ikke beinan mellom beinan'),
('Charles Coulomb',                                     'Jeg spiller feil, derfor er jeg'),
('Alfred Nobel',                                        'Motstanden handler ikke om å spille'),
('Marie Curie',                                         'Alltid ta med alkohol på do! Det har jeg lært av mamma da jeg var liten.'),
('Alan Turing',                                         'Hvis du følger notene, hva skiller deg da fra en maskin?'),
('Arkimedes',                                           'Jeg blir med på ås-SMASH'),
('Gustav Kirchhoff',                                    'Motstanden er en brennende bil på motorveien.'),
('Isaac Newton etter en lang rant på 17.mai',           'TL;DR: Einstein er min erkefiende i Motstanden.'),
('Thomas edison til Nikola Tesla',                      'Hva er ditt forhold til skikk og bruk?'),
('Galileo Galilei',                                     'De situasjonene hvor jeg havner i kake...'),
('Alessandro Volta',                                    'I was a drunk child'),
('Nikola Tesla',                                        'Kirchhoff er the one ring to rule them all!'),
('Marie Curie',                                         'Besteforeldrene mine har én bibel hver – og tre i reserve!'),
('Albert Einstein',                                     'Den eneste grønnesolbrillefabrikken var i kiev'),
('Niels Bohr (med 5 ekstra klesplagg på seg)',          'Jeg fryser så sjukt mye'),
('Linus Torvalds',                                      'Faen! Jeg har lisensiert [ntnu]nettsiden min på MÅKESODD!'),
('Alan Turing',                                         'Jeg drikker bare tre ting: vann, kaffe og øl!'),

-- Copy of the items above
('Gustav K. til Albert E.',                             '"Se på det monsteret der da!"\n\n* Kirchhoff. viser telefonen til Einstein. *\n\nEinstein: "...ehmm... men det er jo..."\nKirchhoff: "Nei, ignorer fargen da!"'),
('Gustav Kirchhoff',                                    'Gustav K.: I dag er den offisielle nynorsk dagen. De har vært smarte ved å velge en dag som...\n*Faraday avbryter*: ...bare kommer 4 ganger i året.'),
('Georg Ohm',                                           'De var flinke! Jeg ble skikkelig kåt ... of guard!'),
('Nikola Tesla',                                        'D einaste en kan stole på, e stål!'),
('Charles Coulomb',                                     'Noen i Motstanden: Hva er SMASH? Kirchhoff: Jeg føler det er litt som en orgie!'),
('Alessandro Volta om Niels Bohr',                      'Mora di er deilig, no offense. At det har kommet ut fra slufsa hennes, det er utrolig!'),
('Niels Bohr om Alfred Nobel',                          'Hvis jeg kan få ta deg i ræven, så kan du få ta meg i ræven.'),
('Alfred Nobel',                                        'Kan man pule en boks tomater? Jeg tror det må være sånn helt ... decent.'),
('Michael Faraday',                                     'Slikk det opp, det går fint!'),
('James Maxwell',                                       'Ikke ta på meg!'),
('Charles Darwin',                                      'Jeg vet ikke hva dette har med bæsj å gjøre.'),
('Thomas Edison',                                       'Nå skal du ta deg et glass rødvin og roe ned den mensinga!'),
('Isaac Newton og Charles Darwin',                      'Newton: Er hun pen eller ikke?\nDarwin svarer: Er det en mann?!'),
('Alan Turing',                                         'Fløte er gøy!'),
('Albert Einstein',                                     'Å nei, har jeg sovnet i stampen?!'), 
('Isaac Newton til Albert Einstein',                    'Du har skikkelig Big Dick-energy!'), 
('Pytagoras',                                           'Arkimedes: Du har ikke behandlet kroppen din sunt; du har dukket masse alkohol.\nPytagoras: Ja, MEN jeg har spist HVER dag kl 1700!'),
('Marie Curie',                                         'Maxwell: jeg må på do.\nCurie: HAR DU HØRT OM BUSKEN?'),
('Heinrich Hertz kl 21:35',                             'Jeg skal inn på samfundet SEINEST kl 2100!'),
('Michael Faraday og Nikola Tesla',                     'Faraday: Hva syns du om staven min?\nTesla: Den er imponerende lang!'),
('Galileo Galilei til Leonardo da Vinci',               'Så du sier man må være muskuløs for å være prest?!'),
('Vekter fra Sykkylven',                                'Lat att grinda, kyra frys!'),
('Stephen Hawking (til sin kone på første øvelse)',     'Jeg tror jeg har blitt med i et korps'),
('Pytagoras til Arkimedes',                             'Du er trommis og du kan ikke slå rytmen til jenter en gang??!'),
('Georg Ohm',                                           'Den konfirmasjonen er det værste SMASH-et jeg har vært på!'),
('James Maxwell',                                       'Det blir spurt om hvem noen har tilgang til P15.\n\nMaxwell: jeg har tilgang, men jeg har mistet studentkortet mitt.\n\nOhm: Hvorfor kjøper du ikke nytt?\n\nMaxwell: Fordi jeg har mistet bankkortet mitt. Men det er ikke alt jeg har mistet, jeg har også mistet lommeboka mi. Men ikke bare har jeg mistet lommeboka mi, jeg har også mistet Jobbkortet mitt. Og ikke bare har jeg mistet Jobbkortet, jeg har også mistet passet mitt. ...men jeg har tilgang.'),
('Charles Coulomb',                                     'Blæsen er det sangkor, er det ikke? '),
('Thomas Edison',                                       'Jeg får litt lyst til å ligge med søsteren min'),
('Marie Curie og Alessandro Volta',                     '*Det snakkes om hakkebakkeskogen*\n\nCurie: Det er turboneger, sant?\n\nVolta: HÆÆÆ, DETTE HAR INGENTING MED TURBONEGER Å GJØRE!\n\nCurie: Jeg sa Thorbjørn Egner...'),
('Stephen Hawking',                                     'Du skjønner ikke, jeg er heavy metal!'),
('Heinrich Hertz',                                      'De vil bli knulla av dyr'),
('Leonhard Euler',                                      'Det huset her er cursed, jeg får hele tida lyst på øl!'),
('Gustav Kirchhoff',                                    'Homenkollmarsjen, det er den eneste sangen jeg trenger noter på.\n\n...Og jeg kan ikke lese noter. Så det er den sangen jeg ikke kan!'),
('Albert Einstein',                                     'I har kun ei skje - og den kjøpte i på Fretex.'),
('Linus Torvalds',                                      'Ikkje ta på elektronikken min!'),
('Linus Torvalds',                                      'Sent på 17. mai kvelden 2021\n\nLinus til Alfred Nobel: Må vi hjem nå? Kan vi ikke vær så snill bli litt lenger?\n\nNobel: Men Alan Turing har dratt hjem\n\nLinus: Vi må dra NÅ, med én gang!!'),
('Joseph Fourier',                                      'Livet er ett elende uten øl, jeg må bare google hva elende er.') , 
('Niels Bohr',                                          'Æ har så lyst tell å sprenge stortinget av å tell!'),
('Isaac Newton',                                        'Det er sykt hvor høy man kan bli på gud ass!'),
('Thomas Edison om han burde stille til leder',         'Møkk er bedre en vakuum.'),
('Linus Torvalds',                                      'Alle e litt Alan Turing når de e full'),
('Leonhard Euler',                                      'Ingen:\n\nIngen:\n\nIngen:\n\nEuler: I mø sø jææækla pisse!'),
('Charles Darwin til Leonardo da Vinci',                'Du har kortslutta naså di du'),
('Thomas Edison',                                       'En... To... Jeg synest det er vanskelig å telle jeg!'),
('Leonardo da Vinci',                                   'Ærlighet varer lenge, men motstanden varer lengest'),
('Overhørt på jubball',                                 'Hva er greia med det orchesteret egentlig'),
('Pytagoras',                                           'Jeg kommer på SMASH!'),
('Georg Ohm',                                           'Kirchhoff: Vi har gitt trelle-navn til lånekappene.\n\nOhm: Det er vanskelig navn, vi kommer aldri til å legge merke til om en av de forsvinner. Dere burde heller gitt de noe vi enkelt husker, slik som bæsj, tiss, promp.\n\nKirchhoff: Dere kan jo finne på et eget navn til den lånekappe dere lager nå.\n\nOhm: Da blir det Bæsj..'),
('Er dere rumpeldunklaget til Smygard??',               'Er dere rumpeldunklaget til Smygard??'),
('Joseph Fourier',                                      'Men.. du har jo ikke beinan mellom beinan'),
('Charles Coulomb',                                     'Jeg spiller feil, derfor er jeg'),
('Alfred Nobel',                                        'Motstanden handler ikke om å spille'),
('Marie Curie',                                         'Alltid ta med alkohol på do! Det har jeg lært av mamma da jeg var liten.'),
('Alan Turing',                                         'Hvis du følger notene, hva skiller deg da fra en maskin?'),
('Arkimedes',                                           'Jeg blir med på ås-SMASH'),
('Gustav Kirchhoff',                                    'Motstanden er en brennende bil på motorveien.'),
('Isaac Newton etter en lang rant på 17.mai',           'TL;DR: Einstein er min erkefiende i Motstanden.'),
('Thomas edison til Nikola Tesla',                      'Hva er ditt forhold til skikk og bruk?'),
('Galileo Galilei',                                     'De situasjonene hvor jeg havner i kake...'),
('Alessandro Volta',                                    'I was a drunk child'),
('Nikola Tesla',                                        'Kirchhoff er the one ring to rule them all!'),
('Marie Curie',                                         'Besteforeldrene mine har én bibel hver – og tre i reserve!'),
('Albert Einstein',                                     'Den eneste grønnesolbrillefabrikken var i kiev'),
('Niels Bohr (med 5 ekstra klesplagg på seg)',          'Jeg fryser så sjukt mye'),
('Linus Torvalds',                                      'Faen! Jeg har lisensiert [ntnu]nettsiden min på MÅKESODD!'),
('Alan Turing',                                         'Jeg drikker bare tre ting: vann, kaffe og øl!'),

-- Copy of the items above
('Gustav K. til Albert E.',                             '"Se på det monsteret der da!"\n\n* Kirchhoff. viser telefonen til Einstein. *\n\nEinstein: "...ehmm... men det er jo..."\nKirchhoff: "Nei, ignorer fargen da!"'),
('Gustav Kirchhoff',                                    'Gustav K.: I dag er den offisielle nynorsk dagen. De har vært smarte ved å velge en dag som...\n*Faraday avbryter*: ...bare kommer 4 ganger i året.'),
('Georg Ohm',                                           'De var flinke! Jeg ble skikkelig kåt ... of guard!'),
('Nikola Tesla',                                        'D einaste en kan stole på, e stål!'),
('Charles Coulomb',                                     'Noen i Motstanden: Hva er SMASH? Kirchhoff: Jeg føler det er litt som en orgie!'),
('Alessandro Volta om Niels Bohr',                      'Mora di er deilig, no offense. At det har kommet ut fra slufsa hennes, det er utrolig!'),
('Niels Bohr om Alfred Nobel',                          'Hvis jeg kan få ta deg i ræven, så kan du få ta meg i ræven.'),
('Alfred Nobel',                                        'Kan man pule en boks tomater? Jeg tror det må være sånn helt ... decent.'),
('Michael Faraday',                                     'Slikk det opp, det går fint!'),
('James Maxwell',                                       'Ikke ta på meg!'),
('Charles Darwin',                                      'Jeg vet ikke hva dette har med bæsj å gjøre.'),
('Thomas Edison',                                       'Nå skal du ta deg et glass rødvin og roe ned den mensinga!'),
('Isaac Newton og Charles Darwin',                      'Newton: Er hun pen eller ikke?\nDarwin svarer: Er det en mann?!'),
('Alan Turing',                                         'Fløte er gøy!'),
('Albert Einstein',                                     'Å nei, har jeg sovnet i stampen?!'), 
('Isaac Newton til Albert Einstein',                    'Du har skikkelig Big Dick-energy!'), 
('Pytagoras',                                           'Arkimedes: Du har ikke behandlet kroppen din sunt; du har dukket masse alkohol.\nPytagoras: Ja, MEN jeg har spist HVER dag kl 1700!'),
('Marie Curie',                                         'Maxwell: jeg må på do.\nCurie: HAR DU HØRT OM BUSKEN?'),
('Heinrich Hertz kl 21:35',                             'Jeg skal inn på samfundet SEINEST kl 2100!'),
('Michael Faraday og Nikola Tesla',                     'Faraday: Hva syns du om staven min?\nTesla: Den er imponerende lang!'),
('Galileo Galilei til Leonardo da Vinci',               'Så du sier man må være muskuløs for å være prest?!'),
('Vekter fra Sykkylven',                                'Lat att grinda, kyra frys!'),
('Stephen Hawking (til sin kone på første øvelse)',     'Jeg tror jeg har blitt med i et korps'),
('Pytagoras til Arkimedes',                             'Du er trommis og du kan ikke slå rytmen til jenter en gang??!'),
('Georg Ohm',                                           'Den konfirmasjonen er det værste SMASH-et jeg har vært på!'),
('James Maxwell',                                       'Det blir spurt om hvem noen har tilgang til P15.\n\nMaxwell: jeg har tilgang, men jeg har mistet studentkortet mitt.\n\nOhm: Hvorfor kjøper du ikke nytt?\n\nMaxwell: Fordi jeg har mistet bankkortet mitt. Men det er ikke alt jeg har mistet, jeg har også mistet lommeboka mi. Men ikke bare har jeg mistet lommeboka mi, jeg har også mistet Jobbkortet mitt. Og ikke bare har jeg mistet Jobbkortet, jeg har også mistet passet mitt. ...men jeg har tilgang.'),
('Charles Coulomb',                                     'Blæsen er det sangkor, er det ikke? '),
('Thomas Edison',                                       'Jeg får litt lyst til å ligge med søsteren min'),
('Marie Curie og Alessandro Volta',                     '*Det snakkes om hakkebakkeskogen*\n\nCurie: Det er turboneger, sant?\n\nVolta: HÆÆÆ, DETTE HAR INGENTING MED TURBONEGER Å GJØRE!\n\nCurie: Jeg sa Thorbjørn Egner...'),
('Stephen Hawking',                                     'Du skjønner ikke, jeg er heavy metal!'),
('Heinrich Hertz',                                      'De vil bli knulla av dyr'),
('Leonhard Euler',                                      'Det huset her er cursed, jeg får hele tida lyst på øl!'),
('Gustav Kirchhoff',                                    'Homenkollmarsjen, det er den eneste sangen jeg trenger noter på.\n\n...Og jeg kan ikke lese noter. Så det er den sangen jeg ikke kan!'),
('Albert Einstein',                                     'I har kun ei skje - og den kjøpte i på Fretex.'),
('Linus Torvalds',                                      'Ikkje ta på elektronikken min!'),
('Linus Torvalds',                                      'Sent på 17. mai kvelden 2021\n\nLinus til Alfred Nobel: Må vi hjem nå? Kan vi ikke vær så snill bli litt lenger?\n\nNobel: Men Alan Turing har dratt hjem\n\nLinus: Vi må dra NÅ, med én gang!!'),
('Joseph Fourier',                                      'Livet er ett elende uten øl, jeg må bare google hva elende er.') , 
('Niels Bohr',                                          'Æ har så lyst tell å sprenge stortinget av å tell!'),
('Isaac Newton',                                        'Det er sykt hvor høy man kan bli på gud ass!'),
('Thomas Edison om han burde stille til leder',         'Møkk er bedre en vakuum.'),
('Linus Torvalds',                                      'Alle e litt Alan Turing når de e full'),
('Leonhard Euler',                                      'Ingen:\n\nIngen:\n\nIngen:\n\nEuler: I mø sø jææækla pisse!'),
('Charles Darwin til Leonardo da Vinci',                'Du har kortslutta naså di du'),
('Thomas Edison',                                       'En... To... Jeg synest det er vanskelig å telle jeg!'),
('Leonardo da Vinci',                                   'Ærlighet varer lenge, men motstanden varer lengest'),
('Overhørt på jubball',                                 'Hva er greia med det orchesteret egentlig'),
('Pytagoras',                                           'Jeg kommer på SMASH!'),
('Georg Ohm',                                           'Kirchhoff: Vi har gitt trelle-navn til lånekappene.\n\nOhm: Det er vanskelig navn, vi kommer aldri til å legge merke til om en av de forsvinner. Dere burde heller gitt de noe vi enkelt husker, slik som bæsj, tiss, promp.\n\nKirchhoff: Dere kan jo finne på et eget navn til den lånekappe dere lager nå.\n\nOhm: Da blir det Bæsj..'),
('Er dere rumpeldunklaget til Smygard??',               'Er dere rumpeldunklaget til Smygard??'),
('Joseph Fourier',                                      'Men.. du har jo ikke beinan mellom beinan'),
('Charles Coulomb',                                     'Jeg spiller feil, derfor er jeg'),
('Alfred Nobel',                                        'Motstanden handler ikke om å spille'),
('Marie Curie',                                         'Alltid ta med alkohol på do! Det har jeg lært av mamma da jeg var liten.'),
('Alan Turing',                                         'Hvis du følger notene, hva skiller deg da fra en maskin?'),
('Arkimedes',                                           'Jeg blir med på ås-SMASH'),
('Gustav Kirchhoff',                                    'Motstanden er en brennende bil på motorveien.'),
('Isaac Newton etter en lang rant på 17.mai',           'TL;DR: Einstein er min erkefiende i Motstanden.'),
('Thomas edison til Nikola Tesla',                      'Hva er ditt forhold til skikk og bruk?'),
('Galileo Galilei',                                     'De situasjonene hvor jeg havner i kake...'),
('Alessandro Volta',                                    'I was a drunk child'),
('Nikola Tesla',                                        'Kirchhoff er the one ring to rule them all!'),
('Marie Curie',                                         'Besteforeldrene mine har én bibel hver – og tre i reserve!'),
('Albert Einstein',                                     'Den eneste grønnesolbrillefabrikken var i kiev'),
('Niels Bohr (med 5 ekstra klesplagg på seg)',          'Jeg fryser så sjukt mye'),
('Linus Torvalds',                                      'Faen! Jeg har lisensiert [ntnu]nettsiden min på MÅKESODD!'),
('Alan Turing',                                         'Jeg drikker bare tre ting: vann, kaffe og øl!');

INSERT INTO ping VALUES ('Pong from the database');