export function strToNumber(str: string | undefined | null): number | undefined {
    if (!str)
        return undefined

    if (!isOnlyNumbers(str))
        return undefined

    return parseInt(str)
}

export function isOnlyNumbers(str: string): boolean {
    return /^[0-9]+$/.test(str);
}

// Generated by github copilot, hope it is correct
type WhitespaceString = "" | " " | "\n" | "\t" | "\r" | "\v" | "\f" | "\u00A0" | "\u2028" | "\u2029" | "\uFEFF";

export function isNullOrWhitespace(str: string | undefined | null): str is undefined | null | WhitespaceString {
    if (!str) {
        return true
    }

    return /^\s*$/.test(str);
}